# Generated by Django 4.2.9 on 2024-02-09 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_creates', models.DateTimeField(auto_now_add=True)),
                ('choice_content', models.CharField(choices=[('TN', 'Танк'), ('HL', 'Лекарь'), ('DD', 'Воин'), ('GM', 'Глава гильдии'), ('QG', 'Квестгивер'), ('BM', 'Кузнец'), ('LW', 'Кожевник'), ('PM', 'Зельевар'), ('CS', 'Заклинатель')], default='TN', max_length=2)),
                ('heading', models.CharField(max_length=64)),
                ('rating', models.IntegerField(default=0)),
                ('content_field', markdownx.models.MarkdownxField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_creates', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
